    # Powershell is used by one of the Github actions so these tasks install it

    - name: Download Powershell
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb

    - name: Install Powershell repo
      apt: deb="/tmp/packages-microsoft-prod.deb"

    - name: Install required system packages
      apt:
        pkg:
          - powershell
        state: latest
        update_cache: true      